-- 003_functions.sql — Compatibility scores
-- Generated by scripts/score_all.js on 2026-03-17T04:26:54.272Z
-- 12331 pairs scored (score_version=1)
--
-- Requires: 001_schema.sql + 002_seed.sql already applied.
-- Run via: supabase db push  OR  paste into Supabase SQL editor.

-- Scoring stored procedure (called by the app for incremental updates)
CREATE OR REPLACE FUNCTION score_new_athlete(new_athlete_id uuid)
RETURNS void AS $$
DECLARE
  a athletes%ROWTYPE;
  b athletes%ROWTYPE;
BEGIN
  SELECT * INTO a FROM athletes WHERE id = new_athlete_id;
  FOR b IN
    SELECT * FROM athletes
    WHERE id != new_athlete_id
      AND discipline = a.discipline
      AND search_status = 'active'
  LOOP
    -- canonical ordering
    DECLARE
      id_a uuid := LEAST(a.id, b.id);
      id_b uuid := GREATEST(a.id, b.id);
    BEGIN
      -- Height score
      DECLARE
        delta numeric := ABS(a.height_cm - b.height_cm);
        h_score numeric;
        l_score numeric;
        r_score numeric;
        total   numeric;
      BEGIN
        -- height
        IF a.discipline = 'pairs' THEN
          IF delta BETWEEN 15 AND 25 THEN h_score := 1.0;
          ELSIF delta < 15 THEN h_score := GREATEST(0, 1 - (15 - delta) / 15.0);
          ELSE h_score := GREATEST(0, 1 - (delta - 25) / 20.0); END IF;
        ELSIF a.discipline = 'ice_dance' THEN
          IF delta BETWEEN 8 AND 18 THEN h_score := 1.0;
          ELSIF delta < 8 THEN h_score := GREATEST(0, 1 - (8 - delta) / 10.0);
          ELSE h_score := GREATEST(0, 1 - (delta - 18) / 15.0); END IF;
        ELSE h_score := GREATEST(0, 1 - delta / 15.0); END IF;
        -- level
        DECLARE
          levels text[] := ARRAY['pre_juvenile','juvenile','intermediate','novice','junior','senior','adult'];
          ia int := array_position(levels, a.skating_level::text);
          ib int := array_position(levels, b.skating_level::text);
          ldelta int := ABS(ia - ib);
        BEGIN
          l_score := CASE ldelta WHEN 0 THEN 1.0 WHEN 1 THEN 0.7 WHEN 2 THEN 0.4 WHEN 3 THEN 0.15 ELSE 0.0 END;
        END;
        -- role
        DECLARE roles text := (ARRAY[a.partner_role::text, b.partner_role::text] ORDER BY 1)[1] || '-' || (ARRAY[a.partner_role::text, b.partner_role::text] ORDER BY 1)[2];
        BEGIN
          r_score := CASE roles
            WHEN 'lady-man' THEN 1.0
            WHEN 'either-man' THEN 0.9 WHEN 'either-lady' THEN 0.9
            WHEN 'either-either' THEN 0.7
            ELSE 0.0 END;
        END;
        total := h_score * 0.35 + l_score * 0.30 + r_score * 0.15 + 0.5 * 0.15 + 0.5 * 0.05;
        INSERT INTO compatibility_scores
          (athlete_a_id, athlete_b_id, height_score, level_score, role_score, location_score, goals_score, total_score, score_version)
        VALUES (id_a, id_b, h_score, l_score, r_score, 0.5, 0.5, ROUND(total::numeric, 3), 1)
        ON CONFLICT (athlete_a_id, athlete_b_id) DO UPDATE SET
          height_score=EXCLUDED.height_score, level_score=EXCLUDED.level_score,
          role_score=EXCLUDED.role_score, total_score=EXCLUDED.total_score,
          score_version=EXCLUDED.score_version, computed_at=now();
      END;
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- To compute scores for ALL athletes after seeding:
-- SELECT score_new_athlete(id) FROM athletes;