/**
 * scripts/generate_seed_sql.js
 *
 * Reads supabase/seed/normalized.json → writes supabase/migrations/002_seed.sql
 * Called as part of building phase 0.4.
 *
 * The SQL:
 *   1. INSERTs all non-flagged records into raw_athletes
 *   2. Promotes them into athletes via the plan's SELECT/INSERT pattern
 *
 * Records with review_flag=true are included in raw_athletes with promoted=false
 * so a human can inspect and manually promote them later.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const NORM_PATH = join(__dirname, '../supabase/seed/normalized.json');
const SQL_PATH  = join(__dirname, '../supabase/migrations/002_seed.sql');

const records = JSON.parse(readFileSync(NORM_PATH, 'utf8'));

function sqlStr(v) {
  if (v == null) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

function sqlNum(v) {
  if (v == null) return 'NULL';
  return String(v);
}

function sqlBool(v) {
  return v ? 'true' : 'false';
}

const lines = [];

lines.push(`-- 002_seed.sql — Seed data from IcePartnerSearch.com scrape`);
lines.push(`-- Generated by scripts/generate_seed_sql.js on ${new Date().toISOString()}`);
lines.push(`-- ${records.length} records total`);
lines.push(`--`);
lines.push(`-- Run AFTER 001_schema.sql.`);
lines.push(`-- Safe to re-run: uses ON CONFLICT DO NOTHING on source_url.`);
lines.push(``);
lines.push(`-- Step 1: Insert into staging table`);
lines.push(`INSERT INTO raw_athletes`);
lines.push(`  (name, discipline, skating_level, partner_role,`);
lines.push(`   height_cm, weight_kg,`);
lines.push(`   location_city, location_state, location_country,`);
lines.push(`   age, contact_note, source, source_url, review_flag, scraped_at)`);
lines.push(`VALUES`);

const valueRows = records.map((r) => {
  return (
    `  (${sqlStr(r.name)}, ${sqlStr(r.discipline)}, ${sqlStr(r.skating_level)}, ${sqlStr(r.partner_role)}, ` +
    `${sqlNum(r.height_cm)}, ${sqlNum(r.weight_kg)}, ` +
    `${sqlStr(r.location_city)}, ${sqlStr(r.location_state)}, ${sqlStr(r.location_country)}, ` +
    `${sqlNum(r.age)}, ${sqlStr(r.contact_note)}, ${sqlStr(r.source)}, ${sqlStr(r.source_url)}, ` +
    `${sqlBool(r.review_flag)}, ${sqlStr(r.scraped_at)})`
  );
});

lines.push(valueRows.join(',\n') + ';');
lines.push(``);
lines.push(`-- ON CONFLICT clause — re-running this file skips already-inserted rows`);
// Postgres doesn't support ON CONFLICT on INSERT ... VALUES with the above syntax
// Rewrite as individual upserts or use a DO NOTHING approach via a CTE:
lines.push(`-- (source_url has a UNIQUE constraint; duplicates silently ignored above`);
lines.push(`--  because we split into individual inserts below)`);

// Actually, rewrite as individual inserts with ON CONFLICT for safety
lines.splice(lines.length - 5); // remove the bulk insert we built — replace with per-row upserts

lines.push(`-- Step 1: Upsert into raw_athletes (idempotent)`);
for (const r of records) {
  lines.push(
    `INSERT INTO raw_athletes ` +
    `(name, discipline, skating_level, partner_role, height_cm, weight_kg, ` +
    `location_city, location_state, location_country, age, contact_note, source, source_url, review_flag, scraped_at) ` +
    `VALUES (${sqlStr(r.name)}, ${sqlStr(r.discipline)}, ${sqlStr(r.skating_level)}, ${sqlStr(r.partner_role)}, ` +
    `${sqlNum(r.height_cm)}, ${sqlNum(r.weight_kg)}, ` +
    `${sqlStr(r.location_city)}, ${sqlStr(r.location_state)}, ${sqlStr(r.location_country)}, ` +
    `${sqlNum(r.age)}, ${sqlStr(r.contact_note)}, ${sqlStr(r.source)}, ${sqlStr(r.source_url)}, ` +
    `${sqlBool(r.review_flag)}, ${sqlStr(r.scraped_at)}) ` +
    `ON CONFLICT (source_url) DO NOTHING;`
  );
}

lines.push(``);
lines.push(`-- Step 2: Promote clean records from staging → athletes table`);
lines.push(`-- (Only records where review_flag = false and required fields are non-null)`);
lines.push(`INSERT INTO athletes`);
lines.push(`  (name, discipline, skating_level, partner_role,`);
lines.push(`   height_cm, weight_kg,`);
lines.push(`   location_city, location_state, location_country,`);
lines.push(`   source, source_url, verified)`);
lines.push(`SELECT`);
lines.push(`  name,`);
lines.push(`  discipline::discipline_type,`);
lines.push(`  skating_level::skating_level,`);
lines.push(`  partner_role::partner_role,`);
lines.push(`  height_cm,`);
lines.push(`  weight_kg,`);
lines.push(`  location_city,`);
lines.push(`  location_state,`);
lines.push(`  location_country,`);
lines.push(`  source,`);
lines.push(`  source_url,`);
lines.push(`  false`);
lines.push(`FROM raw_athletes`);
lines.push(`WHERE review_flag = false`);
lines.push(`  AND name IS NOT NULL`);
lines.push(`  AND discipline IS NOT NULL`);
lines.push(`  AND skating_level IS NOT NULL`);
lines.push(`  AND height_cm IS NOT NULL`);
lines.push(`ON CONFLICT (source_url) DO NOTHING;`);
lines.push(``);
lines.push(`-- Mark promoted records in staging`);
lines.push(`UPDATE raw_athletes SET promoted = true`);
lines.push(`WHERE review_flag = false`);
lines.push(`  AND name IS NOT NULL`);
lines.push(`  AND discipline IS NOT NULL`);
lines.push(`  AND skating_level IS NOT NULL`);
lines.push(`  AND height_cm IS NOT NULL;`);
lines.push(``);
lines.push(`-- Verification counts (run SELECT statements to confirm)`);
lines.push(`-- SELECT COUNT(*) FROM raw_athletes;           -- expect ${records.length}`);
lines.push(`-- SELECT COUNT(*) FROM athletes;               -- expect ${records.filter(r => !r.review_flag && r.name && r.discipline && r.skating_level && r.height_cm).length}`);
lines.push(`-- SELECT COUNT(*) FROM raw_athletes WHERE review_flag = true;  -- expect ${records.filter(r => r.review_flag).length}`);

writeFileSync(SQL_PATH, lines.join('\n'));
console.log(`002_seed.sql written to ${SQL_PATH}`);
console.log(`  ${records.length} rows in raw_athletes`);
console.log(`  ${records.filter(r => !r.review_flag && r.name && r.discipline && r.skating_level && r.height_cm).length} rows promoted to athletes`);
console.log(`  ${records.filter(r => r.review_flag).length} rows held in staging for review`);
