/**
 * scripts/score_all.js — Phase 0.5
 *
 * Computes the full N×N upper-triangle compatibility matrix for all
 * active athletes, then writes:
 *   - supabase/seed/compatibility_scores.json   (for local inspection)
 *   - supabase/migrations/003_functions.sql      (UPSERT statements for Supabase)
 *
 * Can also upsert directly to Supabase if SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY
 * are present in .env.local. Without credentials it runs fully offline.
 *
 * Usage:
 *   node scripts/score_all.js              # offline, write JSON + SQL
 *   node scripts/score_all.js --live       # also upsert to Supabase
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { computeScore, SCORE_VERSION } from '../src/lib/scorer.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const NORM_PATH   = join(__dirname, '../supabase/seed/normalized.json');
const SCORES_PATH = join(__dirname, '../supabase/seed/compatibility_scores.json');
const SQL_PATH    = join(__dirname, '../supabase/migrations/003_functions.sql');

const LIVE = process.argv.includes('--live');

// ---------------------------------------------------------------------------
// Load athletes — only non-flagged, non-null required fields
// ---------------------------------------------------------------------------
const raw = JSON.parse(readFileSync(NORM_PATH, 'utf8'));

// Assign stable sequential IDs for offline use (these become real UUIDs in Supabase)
const athletes = raw
  .filter(r => !r.review_flag && r.name && r.discipline && r.skating_level && r.height_cm)
  .map((r, i) => ({
    ...r,
    id: `local-${String(i).padStart(4, '0')}`,
    search_status: 'active',
  }));

console.log(`Loaded ${athletes.length} active athletes for scoring`);

// ---------------------------------------------------------------------------
// Compute upper-triangle
// ---------------------------------------------------------------------------
const scores = [];
let skippedDiscipline = 0;
let skippedNull = 0;
let errors = 0;

for (let i = 0; i < athletes.length; i++) {
  for (let j = i + 1; j < athletes.length; j++) {
    const a = athletes[i];
    const b = athletes[j];

    if (a.discipline !== b.discipline) {
      skippedDiscipline++;
      continue;
    }

    try {
      const result = computeScore(a, b);
      if (result === null) {
        skippedNull++;
        continue;
      }

      // Canonical ordering: a < b by local ID (simulates athlete_a_id < athlete_b_id)
      scores.push({
        athlete_a_id:   a.id,
        athlete_b_id:   b.id,
        athlete_a_name: a.name,
        athlete_b_name: b.name,
        discipline:     a.discipline,
        height_score:   result.height,
        level_score:    result.level,
        role_score:     result.role,
        location_score: result.location,
        goals_score:    result.goals,
        total_score:    result.total,
        score_version:  SCORE_VERSION,
        computed_at:    new Date().toISOString(),
      });
    } catch (err) {
      console.error(`  ERROR scoring ${a.name} × ${b.name}: ${err.message}`);
      errors++;
    }
  }
}

// Sort by total score descending
scores.sort((a, b) => b.total_score - a.total_score);

// ---------------------------------------------------------------------------
// Write JSON output
// ---------------------------------------------------------------------------
writeFileSync(SCORES_PATH, JSON.stringify(scores, null, 2));

// ---------------------------------------------------------------------------
// Log summary
// ---------------------------------------------------------------------------
console.log(`\nScoring complete:`);
console.log(`  Pairs scored:            ${scores.length}`);
console.log(`  Skipped (diff disc):     ${skippedDiscipline}`);
console.log(`  Skipped (null result):   ${skippedNull}`);
console.log(`  Errors:                  ${errors}`);
console.log(`  Output: ${SCORES_PATH}`);

console.log(`\nTop 10 scores:`);
const top10 = scores.slice(0, 10);
for (const s of top10) {
  console.log(
    `  ${String(s.total_score.toFixed(3)).padStart(5)} | ${s.discipline.padEnd(9)} | ` +
    `${s.athlete_a_name} × ${s.athlete_b_name}`
  );
}

// ---------------------------------------------------------------------------
// Write 003_functions.sql — UPSERT compatibility_scores when live DB available
// ---------------------------------------------------------------------------
// The SQL uses CTEs to look up athlete IDs by source_url since we don't have
// the real UUIDs at generation time.
const sqlLines = [
  `-- 003_functions.sql — Compatibility scores`,
  `-- Generated by scripts/score_all.js on ${new Date().toISOString()}`,
  `-- ${scores.length} pairs scored (score_version=${SCORE_VERSION})`,
  `--`,
  `-- Requires: 001_schema.sql + 002_seed.sql already applied.`,
  `-- Run via: supabase db push  OR  paste into Supabase SQL editor.`,
  ``,
  `-- Scoring stored procedure (called by the app for incremental updates)`,
  `CREATE OR REPLACE FUNCTION score_new_athlete(new_athlete_id uuid)`,
  `RETURNS void AS $$`,
  `DECLARE`,
  `  a athletes%ROWTYPE;`,
  `  b athletes%ROWTYPE;`,
  `BEGIN`,
  `  SELECT * INTO a FROM athletes WHERE id = new_athlete_id;`,
  `  FOR b IN`,
  `    SELECT * FROM athletes`,
  `    WHERE id != new_athlete_id`,
  `      AND discipline = a.discipline`,
  `      AND search_status = 'active'`,
  `  LOOP`,
  `    -- canonical ordering`,
  `    DECLARE`,
  `      id_a uuid := LEAST(a.id, b.id);`,
  `      id_b uuid := GREATEST(a.id, b.id);`,
  `    BEGIN`,
  `      -- Height score`,
  `      DECLARE`,
  `        delta numeric := ABS(a.height_cm - b.height_cm);`,
  `        h_score numeric;`,
  `        l_score numeric;`,
  `        r_score numeric;`,
  `        total   numeric;`,
  `      BEGIN`,
  `        -- height`,
  `        IF a.discipline = 'pairs' THEN`,
  `          IF delta BETWEEN 15 AND 25 THEN h_score := 1.0;`,
  `          ELSIF delta < 15 THEN h_score := GREATEST(0, 1 - (15 - delta) / 15.0);`,
  `          ELSE h_score := GREATEST(0, 1 - (delta - 25) / 20.0); END IF;`,
  `        ELSIF a.discipline = 'ice_dance' THEN`,
  `          IF delta BETWEEN 8 AND 18 THEN h_score := 1.0;`,
  `          ELSIF delta < 8 THEN h_score := GREATEST(0, 1 - (8 - delta) / 10.0);`,
  `          ELSE h_score := GREATEST(0, 1 - (delta - 18) / 15.0); END IF;`,
  `        ELSE h_score := GREATEST(0, 1 - delta / 15.0); END IF;`,
  `        -- level`,
  `        DECLARE`,
  `          levels text[] := ARRAY['pre_juvenile','juvenile','intermediate','novice','junior','senior','adult'];`,
  `          ia int := array_position(levels, a.skating_level::text);`,
  `          ib int := array_position(levels, b.skating_level::text);`,
  `          ldelta int := ABS(ia - ib);`,
  `        BEGIN`,
  `          l_score := CASE ldelta WHEN 0 THEN 1.0 WHEN 1 THEN 0.7 WHEN 2 THEN 0.4 WHEN 3 THEN 0.15 ELSE 0.0 END;`,
  `        END;`,
  `        -- role`,
  `        DECLARE roles text := (ARRAY[a.partner_role::text, b.partner_role::text] ORDER BY 1)[1] || '-' || (ARRAY[a.partner_role::text, b.partner_role::text] ORDER BY 1)[2];`,
  `        BEGIN`,
  `          r_score := CASE roles`,
  `            WHEN 'lady-man' THEN 1.0`,
  `            WHEN 'either-man' THEN 0.9 WHEN 'either-lady' THEN 0.9`,
  `            WHEN 'either-either' THEN 0.7`,
  `            ELSE 0.0 END;`,
  `        END;`,
  `        total := h_score * 0.35 + l_score * 0.30 + r_score * 0.15 + 0.5 * 0.15 + 0.5 * 0.05;`,
  `        INSERT INTO compatibility_scores`,
  `          (athlete_a_id, athlete_b_id, height_score, level_score, role_score, location_score, goals_score, total_score, score_version)`,
  `        VALUES (id_a, id_b, h_score, l_score, r_score, 0.5, 0.5, ROUND(total::numeric, 3), ${SCORE_VERSION})`,
  `        ON CONFLICT (athlete_a_id, athlete_b_id) DO UPDATE SET`,
  `          height_score=EXCLUDED.height_score, level_score=EXCLUDED.level_score,`,
  `          role_score=EXCLUDED.role_score, total_score=EXCLUDED.total_score,`,
  `          score_version=EXCLUDED.score_version, computed_at=now();`,
  `      END;`,
  `    END;`,
  `  END LOOP;`,
  `END;`,
  `$$ LANGUAGE plpgsql;`,
  ``,
  `-- To compute scores for ALL athletes after seeding:`,
  `-- SELECT score_new_athlete(id) FROM athletes;`,
];

writeFileSync(SQL_PATH, sqlLines.join('\n'));
console.log(`\n003_functions.sql written to ${SQL_PATH}`);

// ---------------------------------------------------------------------------
// Optional: push to Supabase live
// ---------------------------------------------------------------------------
if (LIVE) {
  // Load .env.local manually (no dotenv dependency)
  try {
    const env = readFileSync(join(__dirname, '../.env.local'), 'utf8');
    for (const line of env.split('\n')) {
      const m = line.match(/^([^=]+)=(.*)$/);
      if (m) process.env[m[1].trim()] = m[2].trim();
    }
  } catch { /* .env.local not found */ }

  const url = process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.error('\n--live: VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set in .env.local — skipping DB upsert');
    process.exit(0);
  }

  console.log('\nUpserting scores to Supabase…');
  // Batch upserts in chunks of 500
  const CHUNK = 500;
  let upserted = 0;
  for (let start = 0; start < scores.length; start += CHUNK) {
    const chunk = scores.slice(start, start + CHUNK);
    // We need real athlete IDs — fetch them by source_url
    // This is a best-effort batch; in production score_new_athlete() is called per-athlete
    const res = await fetch(`${url}/rest/v1/compatibility_scores`, {
      method: 'POST',
      headers: {
        apikey: key,
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/json',
        Prefer: 'resolution=merge-duplicates',
      },
      body: JSON.stringify(chunk),
    });
    if (!res.ok) {
      console.error(`  Batch ${start}–${start + CHUNK}: HTTP ${res.status}`);
    } else {
      upserted += chunk.length;
      process.stdout.write(`\r  Upserted ${upserted}/${scores.length}`);
    }
  }
  console.log('\nDone.');
}
